server:
  port: 8770


spring:
  zipkin:
    base-url: http://localhost:9411

#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/client?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: sly123321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


foo: foo version 1