spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/